const DASHBOARD_HOME = '/'
const COLORS = '/colors'
const USERS = '/users'
const DASHBOARD_LOGIN = '/auth/login'
const DASHBOARD_REGISTER = '/auth/register'
const DASHBOARD_FORGOT = '/forgot'

const PRIVATE_ROUTES = [DASHBOARD_HOME, USERS, COLORS]
const AUTH_ROUTES = [DASHBOARD_LOGIN, DASHBOARD_REGISTER, DASHBOARD_FORGOT]

export {
  DASHBOARD_HOME,
  DASHBOARD_LOGIN,
  USERS,
  COLORS,
  DASHBOARD_REGISTER,
  PRIVATE_ROUTES,
  AUTH_ROUTES,
}
